### ISSUE TITLE
Error building with Generic Linux installation on Manjaro (Arch Linux)

### ISSUE THREAD

**Issue by PRO2XY** [mongoose-os/mos#7]
Sorry for opening the third issue today, but I feel these three should be handled individually.

I couldn't build mos natively using the `Arch Linux` [installation instructions](https://mongoose-os.com/docs/mongoose-os/quickstart/setup.md#1-download-and-install-mos-tool), so I tried to give the `Generic MacOS/Linux` installation a try.
It installs all ok. 
```
SUCCESS: /home/pranav/.mos/bin/mos is installed.
Run '/home/pranav/.mos/bin/mos --help' to see all available commands.
Run '/home/pranav/.mos/bin/mos' without arguments to start a simplified Web UI installer.
```
But running `mos --help` gave 
```
$ mos --help
The Mongoose OS command line tool 2.13.1.
Update channel: "release". Checking updates... fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x34 pc=0xf5a7bcfa]
```
Running just `mos` **runs ok** and opens up the browser with the Web UI. 
Here I git cloned the demo app1 as per [Getting Started instructions](https://mongoose-os.com/docs/mongoose-os/quickstart/setup.md#4-create-new-app), but when I run `mos build` I again hit the SIGSEGV.

```$ mos build
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0xf760f4d6]

runtime stack:
runtime.throw(0x8ad37d4, 0x2a)
	/usr/lib/go-1.10/src/runtime/panic.go:616 +0x71
runtime.sigpanic()
	/usr/lib/go-1.10/src/runtime/signal_unix.go:372 +0x239

goroutine 22 [syscall]:
runtime.cgocall(0x87f60c0, 0x1b545ee8, 0x8ad20f8)
	/usr/lib/go-1.10/src/runtime/cgocall.go:128 +0x75 fp=0x1b545ecc sp=0x1b545eb4 pc=0x8049f35
net._C2func_getaddrinfo(0x1b80e1d0, 0x0, 0x1b586560, 0x1b60c0b0, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:85 +0x4f fp=0x1b545ee8 sp=0x1b545ecc pc=0x81a153f
net.cgoLookupIPCNAME.func1(0x1b80e1d0, 0x0, 0x1b586560, 0x1b60c0b0, 0x10, 0x10, 0xf)
	/usr/lib/go-1.10/src/net/cgo_unix.go:149 +0x107 fp=0x1b545f10 sp=0x1b545ee8 pc=0x81a6e97
net.cgoLookupIPCNAME(0x1b814040, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/net/cgo_unix.go:149 +0x155 fp=0x1b545f90 sp=0x1b545f10 pc=0x81a27e5
net.cgoIPLookup(0x1b58a480, 0x1b814040, 0xf)
	/usr/lib/go-1.10/src/net/cgo_unix.go:201 +0x2d fp=0x1b545fe0 sp=0x1b545f90 pc=0x81a2d4d
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_386.s:1665 +0x1 fp=0x1b545fe4 sp=0x1b545fe0 pc=0x8098551
created by net.cgoLookupIP
	/usr/lib/go-1.10/src/net/cgo_unix.go:211 +0x8c

...
... Lots more output 
...


exit status 2
Command completed.
```

**Comment by PRO2XY** [comment]
This problem seems to be present since before the repo shift, as [this issue](https://github.com/cesanta/mos-tool/issues/25) addresses.

Surprisingly there doesn't seem to be much activity in the community. I was wanting to have a quick look at Mongoose OS to experience its capabilities and integrate it into our projects. Coming from [this video](https://www.youtube.com/watch?v=kV3IekXJklI) I was expecting to get started really quickly :-)

Perhaps not many people are developing on it from Arch environment. It would be great if someone could help me solve this issue and get mos running!

**Comment by solarkraft** [comment]
I too expected to get started faster. If you're still interested in Mongoose OS and can't get it to compile, you might be interested in [my build](https://mega.nz/#!ntlFkAJJ!6SASbnnZHb-upiUxLb9vp9HT85jm4YrACNcB2zuDkaE).

**Comment by PRO2XY** [comment]
Thanks @solarkraft 
I will give it a go. But for now, my team decided to move away from Mongoose OS due to the lack of a support community. Pity, since it seemed a good tool to base our work on.

**Comment by DrBomb** [comment]
Have you tried building it from sources? I was running a test manjaro box today and I managed to compile it fairly easy. Just follow the commands on the README.

**Comment by bondo11** [comment]
i get this:
```mos ui
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe5 pc=0xe4d3c872]

runtime stack:
runtime.throw(0x8b2f6b2, 0x2a)
	/usr/lib/go-1.14/src/runtime/panic.go:1116 +0x6a
runtime.sigpanic()
	/usr/lib/go-1.14/src/runtime/signal_unix.go:679 +0x39d

goroutine 1 [syscall]:
runtime.cgocall(0x886ade0, 0xa9f7ac0, 0xaad6ab8)
	/usr/lib/go-1.14/src/runtime/cgocall.go:133 +0x67 fp=0xa9f7aac sp=0xa9f7a94 pc=0x804b127
os/user._Cfunc_mygetpwuid_r(0x3e8, 0xaaa18a0, 0xa5e7560, 0x400, 0xaad6ab8, 0x0)
	_cgo_gotypes.go:171 +0x3f fp=0xa9f7ac0 sp=0xa9f7aac pc=0x829715f
os/user.lookupUnixUid.func1.1(0x3e8, 0xaaa18a0, 0xaad6ac0, 0xaad6ab8, 0x805352c)
	/usr/lib/go-1.14/src/os/user/cgo_lookup_unix.go:103 +0xbc fp=0xa9f7ae4 sp=0xa9f7ac0 pc=0x829823c
os/user.lookupUnixUid.func1(0x8a27020)
	/usr/lib/go-1.14/src/os/user/cgo_lookup_unix.go:103 +0x35 fp=0xa9f7afc sp=0xa9f7ae4 pc=0x8298295
os/user.retryWithBuffer(0xaad6ac0, 0xa9f7b68, 0xe7d9ba00, 0x400)
	/usr/lib/go-1.14/src/os/user/cgo_lookup_unix.go:247 +0x2f fp=0xa9f7b24 sp=0xa9f7afc pc=0x8297a0f
os/user.lookupUnixUid(0x3e8, 0x0, 0x0, 0x0)
	/usr/lib/go-1.14/src/os/user/cgo_lookup_unix.go:96 +0xdb fp=0xa9f7b88 sp=0xa9f7b24 pc=0x82974ab
os/user.current(0x0, 0x1, 0x8059b01)
	/usr/lib/go-1.14/src/os/user/cgo_lookup_unix.go:49 +0x45 fp=0xa9f7ba4 sp=0xa9f7b88 pc=0x82973a5
os/user.Current.func1()
	/usr/lib/go-1.14/src/os/user/lookup.go:15 +0x1a fp=0xa9f7bb4 sp=0xa9f7ba4 pc=0x829811a
sync.(*Once).doSlow(0x9394f90, 0x8b4c944)
	/usr/lib/go-1.14/src/sync/once.go:66 +0xda fp=0xa9f7bdc sp=0xa9f7bb4 pc=0x80ad6aa
sync.(*Once).Do(0x9394f90, 0x8b4c944)
	/usr/lib/go-1.14/src/sync/once.go:57 +0x43 fp=0xa9f7be8 sp=0xa9f7bdc pc=0x80ad5c3
os/user.Current(0x0, 0x1, 0x101)
	/usr/lib/go-1.14/src/os/user/lookup.go:15 +0x31 fp=0xa9f7bfc sp=0xa9f7be8 pc=0x8296e91
k8s.io/klog/v2.getUserName.func1()
	/src/vendor/k8s.io/klog/v2/klog_file.go:82 +0x1a fp=0xa9f7c0c sp=0xa9f7bfc pc=0x829cf2a
sync.(*Once).doSlow(0x93ab188, 0x8b4c5fc)
	/usr/lib/go-1.14/src/sync/once.go:66 +0xda fp=0xa9f7c34 sp=0xa9f7c0c pc=0x80ad6aa
sync.(*Once).Do(0x93ab188, 0x8b4c5fc)
	/usr/lib/go-1.14/src/sync/once.go:57 +0x43 fp=0xa9f7c40 sp=0xa9f7c34 pc=0x80ad5c3
k8s.io/klog/v2.getUserName(0xf7f92088, 0x9afc996)
	/src/vendor/k8s.io/klog/v2/klog_file.go:61 +0x2d fp=0xa9f7c4c sp=0xa9f7c40 pc=0x829c50d
k8s.io/klog/v2.logName(0x8afe1f0, 0x4, 0x9709f72b, 0xbfe41045, 0x319cfd, 0x0, 0x93952e0, 0x8, 0x0, 0x80c8317, ...)
	/src/vendor/k8s.io/klog/v2/klog_file.go:107 +0x25 fp=0xa9f7d1c sp=0xa9f7c4c pc=0x829c555
k8s.io/klog/v2.create(0x8afe1f0, 0x4, 0x9709f72b, 0xbfe41045, 0x319cfd, 0x0, 0x93952e0, 0x1, 0x20, 0xaaa1880, ...)
	/src/vendor/k8s.io/klog/v2/klog_file.go:139 +0x182 fp=0xa9f7db4 sp=0xa9f7d1c pc=0x829cae2
k8s.io/klog/v2.(*syncBuffer).rotateFile(0xaaa1880, 0x9709f72b, 0xbfe41045, 0x319cfd, 0x0, 0x93952e0, 0x8c7cd01, 0x73, 0x6)
	/src/vendor/k8s.io/klog/v2/klog.go:1079 +0x6c fp=0xa9f7e20 sp=0xa9f7db4 pc=0x829b5cc
k8s.io/klog/v2.(*loggingT).createFiles(0x93956a0, 0x0, 0x0, 0x80ad714)
	/src/vendor/k8s.io/klog/v2/klog.go:1119 +0x10c fp=0xa9f7e70 sp=0xa9f7e20 pc=0x829baec
k8s.io/klog/v2.(*loggingT).output(0x93956a0, 0x0, 0x0, 0x0, 0xaa31200, 0x92c1539, 0x7, 0x105, 0x0)
	/src/vendor/k8s.io/klog/v2/klog.go:916 +0x553 fp=0xa9f7ed0 sp=0xa9f7e70 pc=0x829aef3
k8s.io/klog/v2.(*loggingT).printf(0x93956a0, 0x0, 0x0, 0x0, 0x8b05b2d, 0xb, 0xa9f7f74, 0x1, 0x1)
	/src/vendor/k8s.io/klog/v2/klog.go:733 +0x11a fp=0xa9f7f0c sp=0xa9f7ed0 pc=0x829a6da
k8s.io/klog/v2.Infof(...)
	/src/vendor/k8s.io/klog/v2/klog.go:1363
main.main()
	/src/cli/main.go:261 +0x2d3 fp=0xa9f7fc8 sp=0xa9f7f0c pc=0x8863ab3
runtime.main()
	/usr/lib/go-1.14/src/runtime/proc.go:203 +0x1fd fp=0xa9f7ff0 sp=0xa9f7fc8 pc=0x807ab7d
runtime.goexit()
	/usr/lib/go-1.14/src/runtime/asm_386.s:1337 +0x1 fp=0xa9f7ff4 sp=0xa9f7ff0 pc=0x80a48a1

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x93956a0)
	/src/vendor/k8s.io/klog/v2/klog.go:1131 +0x6b
created by k8s.io/klog/v2.init.0
	/src/vendor/k8s.io/klog/v2/klog.go:416 +0xe3

goroutine 7 [select]:
go.opencensus.io/stats/view.(*worker).start(0xa83bcc0)
	/src/vendor/go.opencensus.io/stats/view/worker.go:147 +0xb2
created by go.opencensus.io/stats/view.init.0
	/src/vendor/go.opencensus.io/stats/view/worker.go:29 +0x47

goroutine 8 [sleep]:
time.Sleep(0x5f5e100, 0x0)
	/usr/lib/go-1.14/src/runtime/time.go:188 +0xd1
main.main.func1()
	/src/cli/main.go:253 +0x29
created by main.main
	/src/cli/main.go:252 +0x23a
```
